on: 
 push:  # 指定触发事件
    branches:
      - master  # 指定触发 action 的分支
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    # 拉取github仓库代码
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    # 执行依赖安装
    - name: 安装依赖
      run: |
          npm install
        
    # 执行构建步骤
    - name: 构建
      run: |
          npm run build
    # 执行部署
    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4 # 这个action会根据配置自动推送代码到指定分支
      with:
        TOKEN: ${{ secrets.ACCESS_TOKEN }} # 指定密钥
        BASE_BRANCH: master 
        BRANCH: gh-pages  ##指定推送到的远程分支
        FOLDER: dist # 指定构建之后要推送哪个目录的代码
